# Generated by Django 4.1.3 on 2022-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('Department', models.CharField(blank=True, max_length=80, null=True)),
                ('Post', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('ZipCode', models.IntegerField(blank=True, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Active', models.BinaryField(blank=True, default=True, null=True)),
                ('Leave_count', models.IntegerField(blank=True, null=True)),
                ('on_leave', models.BinaryField(blank=True, default=False, null=True)),
            ],
        ),
    ]
