# Generated by Django 4.1.3 on 2022-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='on_leave',
            field=models.BooleanField(null=True),
        ),
    ]
