# Generated by Django 4.1.3 on 2022-12-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_alter_employee_active_alter_employee_on_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
